name: 清理仓库工作流

on:
  workflow_dispatch:
    inputs:
      clean_mode:
        description: "清理模式(amount--保留数量, date--保留天数)："
        required: true
        type: choice
        default: 'amount'
        options:
          - 'amount'
          - 'date'
      clean_to_keep:
        description: "保留最近工作流的天数/数量："
        required: true
        type: string
        default: "0"

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      
      - name: 按保留数量清理工作流
        if: ${{ github.event.inputs.clean_mode == 'amount' }}
        uses: igorjs/gh-actions-clean-workflow@main
        with:
          runs_to_keep: ${{ github.event.inputs.clean_to_keep }}
          runs_older_than: 0

      # 当未设置数量时按天数清理
      - name: 按保留天数清理工作流
        if: ${{ github.event.inputs.clean_mode == 'date'}}
        uses: igorjs/gh-actions-clean-workflow@main
        with:
          runs_to_keep: 0
          runs_older_than: ${{ github.event.inputs.clean_to_keep }}
